team-neutrino/2025-Code

README.md

Add Reefscape documentation

---

2025-Code/src/main/java/frc/robot/command_factories/SuperstructureFactory.java

set up command factory folder

---

README.md

add a readme for CAN IDs and other rio ports

add readme for CAN IDs, DIO, and PWM

---

2025-Code/src/main/java/frc/robot/subsystems/LED.java

LED Default Code

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/subsystems/Climb.java

created a skeleton for climb substystem. Deleted untested things for merge to main meeting.

Climb Skeleton Merge Request

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/Main.java
2025-Code/src/main/java/frc/robot/Robot.java
2025-Code/src/main/java/frc/robot/subsystems/ExampleSubsystem.java
2025-Code/src/main/java/frc/robot/subsystems/Limelight.java

hit ctrl+s on all java files so they are properly formatted

format all .java files

---

2025-Code/.Glass/glass.json
2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/LimelightHelpers.java
2025-Code/src/main/java/frc/robot/command_factories/LimelightFactory.java
2025-Code/src/main/java/frc/robot/subsystems/Limelight.java
2025-Code/src/main/java/frc/robot/util/Subsystem.java

new pull request because other one was a draft

Limelight working 

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/RobotContainer.java
2025-Code/src/main/java/frc/robot/command_factories/ArmFactory.java
2025-Code/src/main/java/frc/robot/command_factories/SuperstructureFactory.java
2025-Code/src/main/java/frc/robot/subsystems/Arm.java
2025-Code/src/main/java/frc/robot/subsystems/Elevator.java

added to elevator:
- limit switch
- feed forward calculations (currently commented out until we have a robot)
- added lots of constants for heights and measurements
added to superstructure factory:
- scoring all levels with arm and elevator subsystems- not yet with wrist + intake due to unfinalized design

Scoring superstructure

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/RobotContainer.java
2025-Code/src/main/java/frc/robot/command_factories/ArmFactory.java
2025-Code/src/main/java/frc/robot/command_factories/SuperstructureFactory.java
2025-Code/src/main/java/frc/robot/subsystems/Arm.java
2025-Code/src/main/java/frc/robot/util/Subsystem.java

Did arm factory

---

2025-Code/vendordeps/REVLib-2025.0.2.json

nothing interesting, but why not

revlib update 2025.0.2

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/subsystems/Arm.java
2025-Code/src/main/java/frc/robot/subsystems/Elevator.java
2025-Code/src/main/java/frc/robot/subsystems/NetworkTables/ArmNT.java
2025-Code/src/main/java/frc/robot/subsystems/NetworkTables/ElevatorNT.java
2025-Code/src/main/java/frc/robot/util/MaxMotionTuner.java
2025-Code/src/main/java/frc/robot/util/PIDTuner.java

Also cleanup some code in ArmNT and ElevatorNT

Max Motion Tuning WORKS

---

2025-Code/src/main/java/frc/robot/subsystems/Climb.java
README.md

it was short. I also updated readme for the PWM port for the ratchet for the servo for the lock for the climb

Updated climb subsystem. Updated lock command to be better with the current spike stuff

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/RobotContainer.java
2025-Code/src/main/java/frc/robot/subsystems/Limelight.java
2025-Code/src/main/java/frc/robot/subsystems/Swerve.java
2025-Code/src/main/java/frc/robot/util/GeneratedSwerveCode/CommandSwerveDrivetrain.java
2025-Code/src/main/java/frc/robot/util/Subsystem.java

Limelight localization2

---

2025-Code/src/main/java/frc/robot/Constants.java

Changed Arm gear ratio from 166.67 to 125

Changed Gearbox

---

2025-Code/src/main/deploy/LED.py
2025-Code/src/main/java/frc/robot/subsystems/LED.java

should turn orange when no game piece, blinks white when coral, blinks teal/turquoise when algae.

made LEDs blink

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/subsystems/Elevator.java

Elevator can

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/RobotContainer.java
2025-Code/src/main/java/frc/robot/command_factories/ClimbFactory.java
2025-Code/src/main/java/frc/robot/subsystems/Climb.java

Changed logic. Position based instead of voltage.

Climb Subsystem Edits

---

2025-Code/src/main/java/frc/robot/RobotContainer.java
2025-Code/src/main/java/frc/robot/subsystems/Swerve.java

Changed from an instant command to a regular command

Fix resetYaw method

---

2025-Code/.Glass/glass.json
2025-Code/src/main/java/frc/robot/NetworkTables.java
2025-Code/src/main/java/frc/robot/RobotContainer.java
2025-Code/src/main/java/frc/robot/util/PDH.java
2025-Code/src/main/java/frc/robot/util/Subsystem.java

Nt cleanup

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/subsystems/Climb.java
2025-Code/src/main/java/frc/robot/subsystems/NetworkTables/ClimbNT.java
2025-Code/src/main/java/frc/robot/util/MotionMagicTuner.java
2025-Code/src/main/java/frc/robot/util/Subsystem.java

added climb nt and also added motion magic tuner for ctre

Finished CLIMB NT

---

2025-Code/src/main/java/frc/robot/subsystems/NetworkTables/ClimbNT.java

changed naming max motion to motion magic.

Changed naming

---

2025-Code/src/main/java/frc/robot/subsystems/Climb.java
2025-Code/src/main/java/frc/robot/subsystems/NetworkTables/ClimbNT.java

Did not apply config to new pid changes when using PID tuner. Also cleaned up some stuff.

Climb nt. crucial mistake

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/subsystems/Arm.java

fixed safeangle so it actually does stuff. makes it safe to use the scoring commands by preventing arm movement until the first stage is up to the second stage. also tuned the arm (for having the physical one on it, andrew if youre reading this they got the arm on)

important arm fixes

---

README.md

Added button map and existing buttons in main branch.

Button map in RM

---

2025-Code/src/main/java/frc/robot/Constants.java

Added values to second limelight

setting limebee

---

2025-Code/simgui-ds.json
2025-Code/src/main/deploy/LED.py
2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/RobotContainer.java
2025-Code/src/main/java/frc/robot/command_factories/ClimbFactory.java
2025-Code/src/main/java/frc/robot/commands/DriveToPointCommand.java
2025-Code/src/main/java/frc/robot/subsystems/LED.java
2025-Code/src/main/java/frc/robot/subsystems/Swerve.java

it is red when going to the point and green when it gets within 5 cm (can be changed) of the target

made it so that it changes color for drive to point

---

2025-Code/src/main/java/frc/robot/RobotContainer.java

Add Back Outtake Command

---

2025-Code/src/main/java/frc/robot/RobotContainer.java
2025-Code/src/main/java/frc/robot/subsystems/Arm.java
2025-Code/src/main/java/frc/robot/subsystems/Elevator.java

new/fixed logic for not hitting elevator/swerve modules with the intake mechanism. yippee

Arm elevator conflicts

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/RobotContainer.java
2025-Code/src/main/java/frc/robot/command_factories/CoralFactory.java
2025-Code/src/main/java/frc/robot/command_factories/SuperstructureFactory.java
2025-Code/src/main/java/frc/robot/commands/DriveToPointCommand.java
2025-Code/src/main/java/frc/robot/subsystems/Arm.java
2025-Code/src/main/java/frc/robot/subsystems/Limelight.java

Limelight cleanup

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/commands/DriveAssistCom.java
2025-Code/src/main/java/frc/robot/subsystems/Arm.java
2025-Code/src/main/java/frc/robot/subsystems/Coral.java
2025-Code/src/main/java/frc/robot/subsystems/LED.java
2025-Code/src/main/java/frc/robot/subsystems/Limelight.java

cleanup cleanup

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/RobotContainer.java
2025-Code/src/main/java/frc/robot/util/DriveToPointCalculator.java

fixed swerve startup delay and coral station inverted arm offset

---

2025-Code/vendordeps/PathplannerLib-2025.2.4.json
2025-Code/vendordeps/Phoenix6-25.3.1.json

update vendor deps

---

2025-Code/src/main/deploy/LED.py

pulled this out of Siwon's branch as something safe to get into `main`

add purple and pink to RPi LED colors

---

2025-Code/src/main/java/frc/robot/Constants.java

fixed some lost angle

---

2025-Code/src/main/java/frc/robot/Constants.java

got the okay from Micah, might edit tomorrow

Adjusted servo

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/command_factories/ClimbFactory.java
2025-Code/src/main/java/frc/robot/subsystems/Climb.java
2025-Code/src/main/java/frc/robot/subsystems/NetworkTables/ClimbNT.java

added new logic and fixed constants. it works

CLIMB FINAL REVISIONS.. maybe

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/commands/DriveToPointCommand.java
2025-Code/src/main/java/frc/robot/util/DriveToPointCalculator.java

multiple point functionality for coral station, works with bumpers, tested a good amount in sim

Intake bumpers

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/RobotContainer.java
2025-Code/src/main/java/frc/robot/command_factories/ClimbFactory.java
2025-Code/src/main/java/frc/robot/subsystems/Climb.java
2025-Code/src/main/java/frc/robot/subsystems/NetworkTables/ClimbNT.java

Climb v2.0

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/RobotContainer.java
2025-Code/src/main/java/frc/robot/command_factories/SuperstructureFactory.java
2025-Code/src/main/java/frc/robot/commands/DriveToPointCommand.java
2025-Code/src/main/java/frc/robot/subsystems/Arm.java
2025-Code/src/main/java/frc/robot/subsystems/Coral.java
2025-Code/src/main/java/frc/robot/subsystems/Elevator.java
2025-Code/src/main/java/frc/robot/util/DriveToPointCalculator.java

non-lambda but still cool ig 🌶️🌶️🌶️🌶️🌶️🌶️🌶️🌶️🌶️🌶️🌶️🌶️🌶️🌶️

Dynamic intake

---

2025-Code/src/main/java/frc/robot/Constants.java
2025-Code/src/main/java/frc/robot/commands/DriveToPointCommand.java
2025-Code/src/main/java/frc/robot/subsystems/Limelight.java

New dynamic angles

---

2025-Code/src/main/java/frc/robot/LimelightHelpers.java

remove unused imports

---

2025-Code/src/main/java/frc/robot/Constants.java

the smallest pull request ever

change elevator default position to 0 and slightly adjust pid to fix arm slop on algae
